### PR TITLE
Feature add newsweek clone

### PR DESCRIPTION
**Pull request by Bluette1**
# Feature add Newsweek clone

The task was to clone the [original page](https://www.newsweek.com/).

This project is mainly about

-  CSS Frameworks in Web Design.

This web page is built using the [Bootstrap](https://getbootstrap.com/) framework.

## Live Demo

[Live Demo](https://rawcdn.githack.com/Bluette1/Newsweek-Clone/d38aad0ca73b6fab9e287abf94db3ae1dab2d17e/index.html)

### CODE REVIEW

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes ♻️ 🚥 

Hi @Bluette1, you have done a really great job 👍 The project responsive and really a clone 👌 Before we could move ahead, we need to address the following minor issues. Find comments below:
* Let us fix the margins of each of the images listed below, most of them are in the ```Mobile size```
cy
cy2
cy3
cy4

cy6
* ```Culture and travel``` spans 1 column on a small screen. Currently, we have 3 columns
cy8
* Let us reduce the size of our CSS file and use more of the bootstrap classes. Let apply the DRY rule
* Let us improve our README file. We could add more social media handles and our email.

Kindly make these changes and submit another code review 🙂 
_Happy coding_ 👩‍💻 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by Bluette1** [comment]
Thank you very much for your feedback @addod19! I'll try to make the recommended changes shortly.

**Comment by sumancrest0001** [comment]
[REQUIRED CHANGES] This project looks beautiful and you have fixed all the issues pointed out by the previous TSE. Since this is a responsive design project, we have to make it exactly similar to that of the original page. I found a minor issue on the navbar on medium and mobile size screen. Please fix the alignment of the navbar components. 
Screenshot from 2020-04-02 17-30-34

But we currently have :point_down:  Please fix it.
Screenshot from 2020-04-02 17-30-21

**Comment by sumancrest0001** [comment]
[Required] Please make these images circular on the 
Screenshot from 2020-04-02 17-31-15
mobile screen. 

**Currently, we have this :point_down:** 
Screenshot from 2020-04-02 17-31-04

**Comment by sumancrest0001** [comment]
once we resolve these issues, we are will get a green signal to move ahead.
:+1: :+1: :+1:
**Feel free to contact me on Slack   suman shrestha**

**Comment by Bluette1** [comment]
Thank you very much @sumancrest0001! I'll try to make the recommended changes shortly.

**Review by christianotieno — COMMENTED** [review]
## Pull Request under review by Christian Otieno (TSE)

**Review by christianotieno — CHANGES_REQUESTED** [review]
# **CHANGES REQUIRED** :warning:
Hey @Bluette1 :wave:
-
You have done a splendid job! :tada: Good job.
We, however, do have some few changes to carry out before we proceed (see review comment).
##
## [REQUIRED] - FIX - Main content section
The contents in our site are not centred, 
This is what it looks like; the general feel 👇 

clone

We should be aiming to achieve this: 👇 

original_newsweek_site

- One way to achieve this could be by the use of [containers](https://www.w3schools.com/bootstrap4/bootstrap_containers.asp), a [bootstrap](https://www.w3schools.com/bootstrap/bootstrap_ref_all_classes.asp) class.

## [REQUIRED] - REMOVE - The Styling in the markup
We have some styling appearing in the markup,: 👇 

styling


- Let's remove them and move them to the CSS file


We are almost getting there. 
Please makes changes and submit another review request.
- If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

**Comment by Dandush03** [comment]
# :red_circle: Status: Required Status :red_circle:
### Hey @emiliocm9  :wave: 
## Great Job So Far :muscle: :+1: 

## Your project looks great! but you haven't changed my college last request, you have to make sure the logo on the nav is centered. if you need some help/ideas of how to do it you can reach me through slack 

## Kindly address these change and submit a new code review

### Happy coding:computer: 

#### Daniel Laloush

**Comment by Bluette1** [comment]
Thank you very much for your feedback @christianotieno and @Dandush03! I have tried to implement the recommended changes and resubmitted the PR for review.

**Review by serdg0 — APPROVED** [review]
**Status: Approved.**
### Great Job Marylene! :muscle: :muscle: :fireworks: :fireworks: 
The project looks great! :100:  
Go on and merge :+1: 
Keep the great work in the next project :muscle:

**Comment by Bluette1** [comment]
Okay, thank you very much @serdg0!

**Pull request merged**
